# Generated by Django 4.2.2 on 2023-07-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_location_alter_blog_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
