# Generated by Django 4.2.2 on 2023-07-18 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequirements',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.category'),
        ),
    ]
