# Generated by Django 4.2.2 on 2023-07-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_blog_created_at_blog_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('remote', 'Remote')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
