# Generated by Django 4.2.2 on 2023-07-18 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_jobrequirements_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequirements',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.category', unique=True),
        ),
    ]
