# Generated by Django 4.2.2 on 2023-07-18 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_jobrequirements_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.category'),
        ),
    ]
