# Generated by Django 4.2.2 on 2023-07-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_category_category_name_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
    ]
