# Generated by Django 4.2.2 on 2023-07-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_jobpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='education_qualification',
            field=models.CharField(default='Bachelor in Science', max_length=500),
            preserve_default=False,
        ),
    ]
