# Generated by Django 4.2.2 on 2023-07-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_name_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='position',
            field=models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('intermediate', 'Intermediate'), ('professional', 'Professional')], default='junior', max_length=55),
            preserve_default=False,
        ),
    ]
