# Generated by Django 4.2.2 on 2023-07-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_jobapplication_education_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='experience',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
