# Generated by Django 4.2.2 on 2023-07-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_jobapplication_education_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='dob',
            field=models.DateField(default='2019-11-11'),
            preserve_default=False,
        ),
    ]
