# Generated by Django 4.2.2 on 2023-07-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_jobapplication_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hashtags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
