# Generated by Django 4.2.2 on 2023-07-02 08:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='defaultpp.jpg', null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
